
[package]
name = "tg-bot-playground"
version = "0.1.0"
authors = ["Aleksei Lebedev <allebdev@gmail.com>"]
edition = "2018"

[features]
#default = ["cli"]
cli=[]
telegram=["tbot"]

[dependencies]
tbot = {version="0.6", optional=true}
tokio = {version="0.2", features=["sync", "macros", "time"]}
chrono = "0.4"
log = "0.4"
env_logger = "0.7"
regex = "1.3"
lazy_static = "1.4.0"
async-trait = "0.1"